name: Kwiki-Infobox
version: 0.01
abstract: slash-like infobox for kwiki
author: Kang-min Liu (gugod@gugod.org)
license: perl
distribution_type: module
requires:
  Kwiki: 0.33
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
